# Generated by Django 3.2.17 on 2023-02-07 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_name', models.CharField(max_length=50, unique=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('ref_id', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kurse',
            },
        ),
        migrations.CreateModel(
            name='Kursleiter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('Kursleiter', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('Tutor', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Benutzer'},
        ),
        migrations.AddField(
            model_name='user',
            name='rolle',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Tutor', 'Tutor'), ('Kursleiter', 'Kursleiter'), ('Dozent', 'Dozent')], default=None, max_length=10, verbose_name='Rolle'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_id', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KursleiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kursleiter_id', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blatt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_name', models.CharField(max_length=200)),
                ('ass_id', models.CharField(max_length=100, unique=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kurs')),
            ],
        ),
    ]
