# Generated by Django 3.2.17 on 2023-02-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230207_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blatt',
            options={'verbose_name_plural': 'Blätter'},
        ),
        migrations.AlterModelOptions(
            name='kursleiter',
            options={'verbose_name_plural': 'Kursleiter'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name_plural': 'Tutoren'},
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='arbeitsstunden',
            field=models.FloatField(default=0),
        ),
    ]
