# Generated by Django 3.2.17 on 2023-02-07 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230207_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dozent',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Dozenten',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
        migrations.AlterModelOptions(
            name='blatt',
            options={'verbose_name_plural': 'Übungsblätter'},
        ),
        migrations.AlterModelOptions(
            name='kursleiterprofile',
            options={'verbose_name_plural': 'Kursleiter Profil'},
        ),
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'verbose_name_plural': 'Tutor Profil'},
        ),
        migrations.AddField(
            model_name='kursleiterprofile',
            name='kurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.kurs'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DozentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(choices=[('Prof', 'Prof'), ('Dr', 'Dr')], default='Prof.', max_length=10, verbose_name='Rolle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dozent Profil',
            },
        ),
    ]
