# Generated by Django 3.2.17 on 2023-02-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurs',
            old_name='kurs_name',
            new_name='kurs',
        ),
    ]
