# Generated by Django 3.2.17 on 2023-02-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_kurs_name_kurs_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='ref_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
