# Generated by Django 3.2.17 on 2023-02-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_kurs_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kursleiterprofile',
            name='Kursleiter_id',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='kurs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.kurs'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dozent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_kursleiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blatt',
            name='kurs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.kurs'),
        ),
        migrations.AlterField(
            model_name='kursleiterprofile',
            name='kurs',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.kurs'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='tutor_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolle',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Tutor', 'Tutor'), ('Kursleiter', 'Kursleiter'), ('Dozent', 'Dozent')], default='Admin', max_length=10, verbose_name='Rolle'),
        ),
    ]
