# Generated by Django 3.2.17 on 2023-02-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230210_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='kurs',
        ),
        migrations.AlterField(
            model_name='kursleiterprofile',
            name='kurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kurs'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='tutor_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
