# Generated by Django 3.2.17 on 2023-02-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230210_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='kurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kurs'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='tutor_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolle',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Tutor', 'Tutor'), ('Kursleiter', 'Kursleiter'), ('Dozent', 'Dozent')], max_length=10, verbose_name='Rolle'),
        ),
    ]
