# Generated by Django 3.2.17 on 2023-02-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230210_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dozentprofile',
            name='titel',
            field=models.CharField(choices=[('Prof', 'Prof'), ('Dr', 'Dr')], default='Prof.', max_length=10, verbose_name='Titel'),
        ),
    ]
